remote_theme: mmistakes/minimal-mistakes@4.26.2
title: Claudia C. Weber
theme_color: '#0e83ac'
description: 


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      #show_sidebar: false
      #menubar: docs_menu
      #hero_height: small
      layout: single
      author_profile: true

plugins:
      - jekyll-include-cache

author:
  name             : #"Claudia C. Weber"
  avatar           : "https://lh6.googleusercontent.com/qb1qFqcNz73JRg-9j25BYRIY0bFt1Ma-PbSVJqxl8tO38JDDdB5Ko1XBXNpcsFHF1Gq0RXP_4vgGAVAF7Z_oPhVI41oRkmAwRDFwtectckVEg5375pmUEKoH8P-yYmjQGA=w1280"
  bio              : "email: first.initial.last [at] gmail.com"
  location         : "Cambridge, England"
  email            : #claudia (dot) c (dot) weber (at) gmail (dot) com
