remote_theme: mmistakes/minimal-mistakes@4.26.2
title: Claudia C. Weber
theme_color: '#0e83ac'
description: 


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      #show_sidebar: false
      #menubar: docs_menu
      #hero_height: small
      layout: single
      author_profile: true

plugins:
      - jekyll-include-cache

author:
  name             : "Claudia C. Weber"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : #"I am an **amazing** person."
  location         : "Cambridge, England"
  email            : claudia (dot) c (dot) weber (at) gmail (dot) com
