remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
title: Claudia C. Weber
theme_color: '#0e83ac'
description: 


defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
      menubar: docs_menu
      hero_height: small
